"""
initial

Revision ID: 4541671124ae
Revises: 
Create Date: 2026-05-11 13:41:59.036559
"""

from __future__ import annotations

# Revision identifiers, used by Alembic.
revision: str = "4541671124ae"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Run upgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Run downgrade migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
